export const SHORTEN_URL = 'SHORTEN_URL';
export const REDIRECT_URL = 'REDIRECT_URL';
export const DISPLAY_ERR = 'DISPLAY_ERR';
export const SHORTENER_ERROR = 'SHORTENER_ERROR';
export const SHORTENER_LOADING = 'SHORTENER_LOADING';
export const API_LOADING = 'API_LOADING';